
//https://elixir.bootlin.com/linux/v6.6-rc1/source/include/linux/socket.h#L189
pub const AF_UNSPEC: u16 = 0;
pub const AF_UNIX: u16 = 1;      /* Unix domain sockets          */
pub const AF_LOCAL: u16 = 1;     /* POSIX name for AF_UNIX       */
pub const AF_INET: u16 = 2;      /* Internet IP Protocol         */
pub const AF_AX25: u16 = 3;      /* Amateur Radio AX.25          */
pub const AF_IPX: u16 = 4;       /* Novell IPX                   */
pub const AF_APPLETALK: u16 = 5; /* AppleTalk DDP                */
pub const AF_NETROM: u16 = 6;    /* Amateur Radio NET/ROM         */
pub const AF_BRIDGE: u16 = 7;    /* Multiprotocol bridge         */
pub const AF_ATMPVC: u16 = 8;    /* ATM PVCs                     */
pub const AF_X25: u16 = 9;       /* Reserved for X.25 project    */
pub const AF_INET6: u16 = 10;    /* IP version 6                 */
pub const AF_ROSE: u16 = 11;     /* Amateur Radio X.25 PLP       */
pub const AF_DECnet: u16 = 12;   /* Reserved for DECnet project  */
pub const AF_NETBEUI: u16 = 13;  /* Reserved for 802.2LLC project*/
pub const AF_SECURITY: u16 = 14; /* Security callback pseudo AF  */
pub const AF_KEY: u16 = 15;      /* PF_KEY key management API    */
pub const AF_NETLINK: u16 = 16;
pub const AF_ROUTE: u16 = AF_NETLINK; /* Alias to emulate 4.4BSD */
pub const AF_PACKET: u16 = 17;   /* Packet family                */
pub const AF_ASH: u16 = 18;      /* Ash                          */
pub const AF_ECONET: u16 = 19;   /* Acorn Econet                 */
pub const AF_ATMSVC: u16 = 20;   /* ATM SVCs                     */
pub const AF_RDS: u16 = 21;      /* RDS sockets                  */
pub const AF_SNA: u16 = 22;      /* Linux SNA Project (nutters!) */
pub const AF_IRDA: u16 = 23;     /* IRDA sockets                 */
pub const AF_PPPOX: u16 = 24;    /* PPPoX sockets                */
pub const AF_WANPIPE: u16 = 25;  /* Wanpipe API Sockets          */
pub const AF_LLC: u16 = 26;      /* Linux LLC                    */
pub const AF_IB: u16 = 27;       /* Native InfiniBand address    */
pub const AF_MPLS: u16 = 28;     /* MPLS                         */
pub const AF_CAN: u16 = 29;      /* Controller Area Network      */
pub const AF_TIPC: u16 = 30;     /* TIPC sockets                 */
pub const AF_BLUETOOTH: u16 = 31;/* Bluetooth sockets            */
pub const AF_IUCV: u16 = 32;     /* IUCV sockets                 */
pub const AF_RXRPC: u16 = 33;    /* RxRPC sockets                */
pub const AF_ISDN: u16 = 34;     /* mISDN sockets                */
pub const AF_PHONET: u16 = 35;   /* Phonet sockets               */
pub const AF_IEEE802154: u16 = 36;/* IEEE802154 sockets          */
pub const AF_CAIF: u16 = 37;     /* CAIF sockets                 */
pub const AF_ALG: u16 = 38;      /* Algorithm sockets            */
pub const AF_NFC: u16 = 39;      /* NFC sockets                  */
pub const AF_VSOCK: u16 = 40;    /* vSockets                     */
pub const AF_KCM: u16 = 41;      /* Kernel Connection Multiplexor*/
pub const AF_QIPCRTR: u16 = 42;  /* Qualcomm IPC Router          */
pub const AF_SMC: u16 = 43;      /* smc sockets                  */
pub const AF_XDP: u16 = 44;      /* XDP sockets                  */
pub const AF_MCTP: u16 = 45;     /* Management component transport protocol */

pub const AF_MAX: u16 = 46;      /* For now.. */
